### ISSUE TITLE
Guidance bar example for master/details view (DocWiki for example)

### ISSUE THREAD

**Issue by markleusink** [Isometrica/ui-controls#1]
Not sure if you're already working on this, but can you create an example on how the new guidance bar would work in a master/detail view (like the DocWiki, risk register, etc.)?

The height of the guidance bar is now dynamic (based on the amount of content) and the master/detail views have independent scrolling columns. That mechanism is based on a container div with a `position:fixed` and an exact top offset on it.

**Comment by jackherbert** [comment]
We've implemented flexbox instead, so this should no longer be an issue
